# S: Build Lifecycle
# E: Build LifeCycle

language: node_js
node_js:
  - stable
cache: npm
branches:
  only:
    - blog # build master branch only
script:
  - hexo clean
  - hexo g -d
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  target-branch: master
  keep-history: true
  on:
    branch: blog
  local-dir: public
