# S: Build Lifecycle
# E: Build LifeCycle

language: node_js
node_js:
  - stable
cache: npm
branches:
  only:
    - master # build master branch only
script:
  - hexo clean
  - hexo g
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
  local-dir: public
